
service: auction-service

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  memorySize: 256
  stage: ${opt:stage, 'dev'}
  region: eu-west-2
  environment:
    AUCTIONS_TABLE_NAME: ${self:custom.AuctionsTable.name}
    AUCTIONS_BUCKET_NAME: ${self:custom.AuctionsBucket.name}
  iam:
    role:
      statements:
      - ${file(iam/AuctionsTableIAM.yml):AuctionsTableIAM}
      - ${file(iam/AuctionsBucketIAM.yml):AuctionsBucketIAM}

functions:
  createAuction:
    handler: src/handlers/createAuction.handler
    events:
      - http:
          path: /auctions
          method: POST
          cors: true # configure cors on endpoint
          authorizer: ${self:custom.authorizer} # specify authorization midddlware lambda function - using Function Arn
  getAuctions:
    handler: src/handlers/getAuctions.handler
    events:
      - http:
          path: /auctions
          method: GET
          cors: true # configure cors on endpoint
          authorizer: ${self:custom.authorizer} # specify authorization midddlware lambda function - using Function Arn
  getAuction:
    handler: src/handlers/getAuction.handler
    events:
      - http:
          path: /auctions/{auctionId}
          method: GET
          cors: true # configure cors on endpoint
          authorizer: ${self:custom.authorizer} # specify authorization midddlware lambda function - using Function Arn
  placeBid:
    handler: src/handlers/placeBid.handler
    events:
      - http:
          path: /auctions/{auctionId}/bid
          method: PATCH
          cors: true # configure cors on endpoint
          authorizer: ${self:custom.authorizer} # specify authorization midddlware lambda function - using Function Arn
  uploadAuctionPicture:
    handler: src/handlers/uploadAuctionPicture.handler
    events:
      - http:
          path: /auctions/{auctionId}/picture
          method: PATCH
          cors: true # configure cors on endpoint
          authorizer: ${self:custom.authorizer} # specify authorization midddlware lambda function - using Function Arn
  processAuctions:
    handler: src/handlers/processAuctions.handler
    events:
      # - schedule: rate(1 minute)

resources:
  Resources:
    AuctionsTable: ${file(resources/AuctionsTable.yml):AuctionsTable}
    AuctionsBucket: ${file(resources/AuctionsBucket.yml):AuctionsBucket}
    AuctionsBucketPolicy: ${file(resources/AuctionsBucket.yml):AuctionsBucketPolicy}

custom:
  authorizer: arn:aws:lambda:eu-west-2:676179010844:function:auth-service-dev-auth
  AuctionsTable: 
    name:
      Ref: AuctionsTable
    arn: 
      Fn::GetAtt: [AuctionsTable, Arn]
  AuctionsBucket: 
    name: auctions-bucket-gh576j-${self:provider.stage} # Ensure that bucket name is all lowercase
